// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {sync} from '../models';

export function BuildSite():Promise<void>;

export function ClearCustomCSS():Promise<void>;

export function ConnectToPeer(arg1:string,arg2:number):Promise<void>;

export function CreateNewFile(arg1:string):Promise<boolean>;

export function DisconnectFromPeer(arg1:string):Promise<void>;

export function ExportPDF(arg1:string):Promise<string>;

export function ExportPreviewHTML(arg1:string):Promise<string>;

export function GetASRStatus():Promise<main.ASRStatus>;

export function GetAudioFileURL(arg1:string):Promise<string>;

export function GetConnectedPeers():Promise<Array<sync.Peer>>;

export function GetCustomCSS():Promise<string>;

export function GetFileList():Promise<Array<main.FileItem>>;

export function GetGraphData():Promise<main.GraphData>;

export function ImportAudioBase64(arg1:string,arg2:string):Promise<string>;

export function ImportAudioFile(arg1:string):Promise<string>;

export function InitProject():Promise<void>;

export function IsRecording():Promise<boolean>;

export function LoadFile(arg1:string):Promise<string>;

export function LogJS(arg1:string,arg2:string):Promise<void>;

export function PreviewMarkdown(arg1:string):Promise<string>;

export function ResolveConflict(arg1:string,arg2:string):Promise<void>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;

export function SetCustomCSS(arg1:string):Promise<void>;

export function StartRecording():Promise<void>;

export function StopRecording():Promise<string>;
