// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {sync} from '../models';
import {main} from '../models';

export function BuildSite():Promise<void>;

export function ConnectToPeer(arg1:string,arg2:number):Promise<void>;

export function DisconnectFromPeer(arg1:string):Promise<void>;

export function GetConnectedPeers():Promise<Array<sync.Peer>>;

export function GetFileList():Promise<Array<main.FileItem>>;

export function GetGraphData():Promise<main.GraphData>;

export function InitProject():Promise<void>;

export function LoadFile(arg1:string):Promise<string>;

export function PreviewMarkdown(arg1:string):Promise<string>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;
