package main

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
)

type ephyMutationUATAction struct {
	CandidateID string `json:"candidate_id"`
	Decision    string `json:"decision"`
}

type ephyMutationUATManifest struct {
	SchemaVersion string                  `json:"schema_version"`
	Actions       []ephyMutationUATAction `json:"actions"`
}

// TestEphyMutationUATBridge is an opt-in bridge for ephy-runtime's cross-app
// acceptance script．Normal test runs skip it; the UAT supplies a private
// temporary data root containing proposals generated by Ephy itself．
func TestEphyMutationUATBridge(t *testing.T) {
	dataRoot := os.Getenv("KARTE_MUTATION_UAT_ROOT")
	if dataRoot == "" {
		t.Skip("KARTE_MUTATION_UAT_ROOT is not set")
	}
	resolvedRoot, err := filepath.Abs(dataRoot)
	if err != nil {
		t.Fatal(err)
	}
	manifestPath := filepath.Join(resolvedRoot, ".mdsys", "ephy", "mutation-uat-manifest.json")
	encoded, err := os.ReadFile(manifestPath)
	if err != nil {
		t.Fatal(err)
	}
	var manifest ephyMutationUATManifest
	if err := json.Unmarshal(encoded, &manifest); err != nil {
		t.Fatal(err)
	}
	if manifest.SchemaVersion != "1.0" || len(manifest.Actions) != 3 {
		t.Fatalf("unexpected mutation UAT manifest: %#v", manifest)
	}

	app := NewApp()
	app.root = resolvedRoot
	app.dataDir = resolvedRoot
	inbox, err := app.ListEphyProposals()
	if err != nil {
		t.Fatal(err)
	}
	if len(inbox.Errors) != 0 {
		t.Fatalf("Ephy proposals were not reviewable: %#v", inbox.Errors)
	}
	reviews := make(map[string]struct {
		frontmatter map[string]any
		body        string
	}, len(inbox.Proposals))
	for _, review := range inbox.Proposals {
		reviews[review.Proposal.CandidateID] = struct {
			frontmatter map[string]any
			body        string
		}{review.Proposal.ProposedFrontmatter, review.Proposal.ProposedBody}
	}
	if len(reviews) != len(manifest.Actions) {
		t.Fatalf("review surface did not expose every UAT proposal: got=%d want=%d", len(reviews), len(manifest.Actions))
	}

	for _, action := range manifest.Actions {
		review, ok := reviews[action.CandidateID]
		if !ok {
			t.Fatalf("candidate %s was missing from Karte review", action.CandidateID)
		}
		switch action.Decision {
		case "accept":
			receipt, acceptErr := app.AcceptEphyProposal(action.CandidateID, review.frontmatter, review.body)
			if acceptErr != nil {
				t.Fatalf("accept %s: %v", action.CandidateID, acceptErr)
			}
			if receipt.Result != "accepted" || receipt.DocID == nil || receipt.RelativePath == nil || receipt.ResultingSHA256 == nil {
				t.Fatalf("accepted receipt is incomplete: %#v", receipt)
			}
		case "reject":
			receipt, rejectErr := app.RejectEphyProposal(action.CandidateID, "Rejected by the cross-app human-review UAT.")
			if rejectErr != nil {
				t.Fatalf("reject %s: %v", action.CandidateID, rejectErr)
			}
			if receipt.Result != "rejected" || receipt.ResultingSHA256 != nil {
				t.Fatalf("rejected receipt is invalid: %#v", receipt)
			}
		default:
			t.Fatalf("unsupported UAT decision %q", action.Decision)
		}
	}
}
