package write

import (
	"fmt"
	"os"
	"path/filepath"
	"time"

	"karte/internal/agent/project"
	"karte/internal/agent/rag"
	"karte/internal/frontmatter"

	"github.com/google/uuid"
)

// CreateDocumentResult represents the result of creating a document
type CreateDocumentResult struct {
	DocID   string `json:"doc_id"`
	RelPath string `json:"rel_path"`
	Rev     int    `json:"rev"`
}

// Manager manages document writing
type Manager struct {
	dataDir string
	project *project.Manager
	rag     *rag.Engine
}

// NewManager creates a new write manager
func NewManager(dataDir string, projMgr *project.Manager, ragEngine *rag.Engine) (*Manager, error) {
	// Ensure content/zero directory exists
	zeroDir := filepath.Join(dataDir, "content", "zero")
	if err := os.MkdirAll(zeroDir, 0755); err != nil {
		return nil, fmt.Errorf("failed to create content/zero directory: %w", err)
	}

	return &Manager{
		dataDir: dataDir,
		project: projMgr,
		rag:     ragEngine,
	}, nil
}

// CreateDocument creates a new document in content/zero/
func (m *Manager) CreateDocument(projectID, pathHint, markdown string, meta map[string]interface{}, requestID string) (*CreateDocumentResult, error) {
	// Generate filename: {YYYYMMDD-HHMMSS}_{short_id}.md
	now := time.Now()
	shortID := uuid.New().String()[:8]
	filename := fmt.Sprintf("%s_%s.md", now.Format("20060102-150405"), shortID)

	// Use path hint if provided (sanitized)
	if pathHint != "" {
		// Sanitize path hint
		base := filepath.Base(pathHint)
		ext := filepath.Ext(base)
		if ext == "" {
			ext = ".md"
		}
		base = base[:len(base)-len(ext)]
		// Simple sanitization: remove dangerous characters
		sanitized := ""
		for _, r := range base {
			if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '-' || r == '_' {
				sanitized += string(r)
			}
		}
		if sanitized != "" {
			filename = fmt.Sprintf("%s_%s%s", now.Format("20060102-150405"), sanitized, ext)
		}
	}

	relPath := filepath.Join("content", "zero", filename)
	fullPath := filepath.Join(m.dataDir, relPath)

	// Create frontmatter
	fm := &frontmatter.FrontMatter{
		Raw: make(map[string]interface{}),
	}

	// Set required fields
	fm.Raw["created_by"] = "zero"
	fm.Raw["request_id"] = requestID
	fm.Raw["generated_at"] = now.UTC().Format(time.RFC3339)
	fm.Raw["project_id"] = projectID

	// Add RAG sources if provided
	if ragSources, ok := meta["rag_sources"]; ok {
		fm.Raw["rag_sources"] = ragSources
	}

	// Add any other meta fields
	for k, v := range meta {
		if k != "rag_sources" {
			fm.Raw[k] = v
		}
	}

	// Format frontmatter
	frontmatterStr := frontmatter.FormatFrontMatter(fm)

	// Combine frontmatter and markdown
	content := frontmatterStr + markdown

	// Atomic write: write to temp file first, then rename
	tempPath := fullPath + ".tmp"
	if err := os.WriteFile(tempPath, []byte(content), 0644); err != nil {
		return nil, fmt.Errorf("failed to write temp file: %w", err)
	}

	if err := os.Rename(tempPath, fullPath); err != nil {
		os.Remove(tempPath)
		return nil, fmt.Errorf("failed to rename temp file: %w", err)
	}

	// Extract doc_id from frontmatter (will be generated by Karte on next load)
	// For now, we'll use a placeholder
	docID := uuid.New().String()

	// Update RAG index asynchronously (will be implemented in phase 2)
	go func() {
		_ = m.rag.UpdateIndex(projectID)
	}()

	return &CreateDocumentResult{
		DocID:   docID,
		RelPath: filepath.ToSlash(relPath),
		Rev:     1,
	}, nil
}
