// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildSite() {
  return window['go']['main']['App']['BuildSite']();
}

export function ConnectToPeer(arg1, arg2) {
  return window['go']['main']['App']['ConnectToPeer'](arg1, arg2);
}

export function DisconnectFromPeer(arg1) {
  return window['go']['main']['App']['DisconnectFromPeer'](arg1);
}

export function GetConnectedPeers() {
  return window['go']['main']['App']['GetConnectedPeers']();
}

export function GetFileList() {
  return window['go']['main']['App']['GetFileList']();
}

export function CreateNewFile(arg1) {
  return window['go']['main']['App']['CreateNewFile'](arg1);
}

export function GetGraphData() {
  return window['go']['main']['App']['GetGraphData']();
}

export function InitProject() {
  return window['go']['main']['App']['InitProject']();
}

export function LoadFile(arg1) {
  return window['go']['main']['App']['LoadFile'](arg1);
}

export function PreviewMarkdown(arg1) {
  return window['go']['main']['App']['PreviewMarkdown'](arg1);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}
