# .github/workflows/sync-labels.yml
name: Sync labels

on:
  push:
    paths:
      - ".github/labels.yml"
      - ".github/workflows/sync-labels.yml"
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Sync labels
        uses: crazy-max/ghaction-github-labeler@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labels.yml
          skip-delete: false  # 不要ラベル削除
